### ISSUE TITLE
How does the driver capture data from the interface in this driver program? If you know, thank you very much.

### ISSUE THREAD

**Issue by hulahulahulala** [robot9706/VirtualCameraDriver#13]
How does the driver capture data from the interface in this driver program? If you know, thank you very much. I am a driver beginner.

**Comment by robot9706** [comment]
Data is passed to the driver through a DirectShow Filter property.

**Comment by hulahulahulala** [comment]
> Data is passed to the driver through a DirectShow Filter property.
After long-term learning and debugging, I found that my driver hardware status is stopped, which makes it impossible for me to obtain images in Windows camera applications. What are the possible reasons? How to conduct analysis?
Besides, I would like to ask, what are the supported formats for images? Jpg, png, jpeg? Are there strict requirements for format?
![image](https://github.com/robot9706/VirtualCameraDriver/assets/50671858/fb11f8bc-dc38-44cb-8c59-51a64b1d7577)

**Comment by robot9706** [comment]
Take a look at the hwsim `Start` function, some memory allocation could fail there.

The image format is RGB888. Also it has to be the same resolution as the buffer in the driver interface, so by default 1280x720.

Debugging is hard since it's a driver, you can log to the Windows Event Log, also I beleive if you are running your driver on a different PC you can somehow attach to it and debug it line by line, but I never tried this.
