### ISSUE TITLE
Does it support audio？

### ISSUE THREAD

**Issue by a2448825647** [robot9706/VirtualCameraDriver#8]
Does it support audio？

**Comment by robot9706** [comment]
Nope, video only.

**Comment by a2448825647** [comment]
Thank you for your reply! My goal is to forward the audio and video from a virtual camera. I made some modifications to your code and now I can capture video data from other virtual cameras. Can you please guide me on how to make it support audio? Or could you suggest something for me to search for related information?

**Comment by robot9706** [comment]
Since this is a video driver it has nothing to do with audio, so you'd need to implement a whole audio source yourself. The official WDK samples repo has something for that: https://github.com/microsoft/Windows-driver-samples/tree/main/audio/simpleaudiosample

But you could also use a virtual audio cable driver or seomthing.

**Comment by a2448825647** [comment]
Thank you! This will be very helpful for me. I will try to implement it.
